# Copyright 2019 Splunk, Inc.
#
# Use of this source code is governed by a BSD-2-clause-style
# license that can be found in the LICENSE-BSD2 file or at
# https://opensource.org/licenses/BSD-2-Clause

from jinja2 import Environment

from .sendmessage import *
from .splunkutils import *

env = Environment(extensions=['jinja2_time.TimeExtension'])
# Sourced from the internet non customer data
# <29>1 2017-10-06T11:21:16.0Z SERVERMCAFEE01 EPOEvents - EventFwd [agentInfo@3401 tenantId="1"] <?xml version="1.0" encoding="UTF-8"?><EPOevent><MachineInfo><MachineName>TS01</MachineName><AgentGUID>{768ab1ba-31aa-11e7-2f62-00505696c547}</AgentGUID><IPAddress>10.x.x.x</IPAddress><OSName>Windows 2008 R2</OSName><UserName>SYSTEM</UserName><TimeZoneBias>420</TimeZoneBias><RawMACAddress></RawMACAddress></MachineInfo><SoftwareInfo ProductName="McAfee Endpoint Security" ProductVersion="10.5.0" ProductFamily="TVD"><CommonFields><Analyzer>ENDP_AM_1050</Analyzer><AnalyzerName>McAfee Endpoint Security</AnalyzerName><AnalyzerVersion>10.5.0</AnalyzerVersion><AnalyzerHostName>TS01</AnalyzerHostName><AnalyzerEngineVersion>5900.7806</AnalyzerEngineVersion><AnalyzerDetectionMethod>On-Demand Scan</AnalyzerDetectionMethod><AnalyzerDATVersion>3125.0</AnalyzerDATVersion></CommonFields><Event><EventID>1278</EventID><Severity>3</Severity><GMTTime>2017-10-06T11:17:35</GMTTime><CommonFields><ThreatCategory>av.detect</ThreatCategory><ThreatEventID>1278</ThreatEventID><ThreatSeverity>2</ThreatSeverity><ThreatName>EICAR test file</ThreatName><ThreatType>test</ThreatType><DetectedUTC>2017-10-06T11:17:35Z</DetectedUTC><ThreatActionTaken>IDS_ALERT_ACT_TAK_DEL</ThreatActionTaken><ThreatHandled>True</ThreatHandled><SourceHostName>TS01</SourceHostName><SourceProcessName>On-Demand Scan</SourceProcessName><TargetHostName>TS01</TargetHostName><TargetUserName>CASAA\mohab</TargetUserName><TargetFileName>C:\Users\mohab\Desktop\dell.com</TargetFileName></CommonFields><CustomFields target="EPExtendedEventMT"><BladeName>IDS_BLADE_NAME_SPB</BladeName><AnalyzerContentCreationDate>2017-10-04T15:46:00Z</AnalyzerContentCreationDate><AnalyzerGTIQuery>False</AnalyzerGTIQuery><ThreatDetectedOnCreation>False</ThreatDetectedOnCreation><TargetName>dell.com</TargetName><TargetPath>C:\Users\mohab\Desktop</TargetPath><TargetHash>01c65da52c8f3e5959ce9bb405ba6372</TargetHash><TargetFileSize>70</TargetFileSize><TargetModifyTime>2017-10-06T11:16:03Z</TargetModifyTime><TargetAccessTime>2017-10-06T11:16:03Z</TargetAccessTime><TargetCreateTime>2017-10-06T11:16:03Z</TargetCreateTime><Cleanable>False</Cleanable><TaskName>IDS_ODS_TASK_NAME_RIGHT_CLICK</TaskName><FirstAttemptedAction>IDS_ALERT_THACT_ATT_CLE</FirstAttemptedAction><FirstActionStatus>False</FirstActionStatus><SecondAttemptedAction>IDS_ALERT_THACT_ATT_DEL</SecondAttemptedAction><SecondActionStatus>True</SecondActionStatus><AttackVectorType>4</AttackVectorType><DurationBeforeDetection>92</DurationBeforeDetection><NaturalLangDescription>IDS_NATURAL_LANG_ODS_DETECTION_DELETED|TargetName=dell.com|TargetPath=C:\Users\mohab\Desktop|ThreatName=EICAR test file|ThreatType=test|TaskName=IDS_ODS_TASK_NAME_RIGHT_CLICK|TargetUserName=CASAA\mohab</NaturalLangDescription><AccessRequested></AccessRequested><AMCoreContentVersion>3125.0</AMCoreContentVersion></CustomFields></Event></SoftwareInfo></EPOevent>
def test_mcafee_epo(record_property, setup_wordlist, get_host_key, setup_splunk):
    host = get_host_key

    mt = env.from_string(
        "{{ mark }} {% now 'utc', '%Y-%m-%dT%H:%M:%S' %}.0Z {{ host }} EPOEvents - EventFwd [agentInfo@3401 tenantId=\"1\"] <?xml version=\"1.0\" encoding=\"UTF-8\"?><EPOevent><MachineInfo><MachineName>TS01</MachineName><AgentGUID>{768ab1ba-31aa-11e7-2f62-00505696c547}</AgentGUID><IPAddress>10.x.x.x</IPAddress><OSName>Windows 2008 R2</OSName><UserName>SYSTEM</UserName><TimeZoneBias>420</TimeZoneBias><RawMACAddress></RawMACAddress></MachineInfo><SoftwareInfo ProductName=\"McAfee Endpoint Security\" ProductVersion=\"10.5.0\" ProductFamily=\"TVD\"><CommonFields><Analyzer>ENDP_AM_1050</Analyzer><AnalyzerName>McAfee Endpoint Security</AnalyzerName><AnalyzerVersion>10.5.0</AnalyzerVersion><AnalyzerHostName>TS01</AnalyzerHostName><AnalyzerEngineVersion>5900.7806</AnalyzerEngineVersion><AnalyzerDetectionMethod>On-Demand Scan</AnalyzerDetectionMethod><AnalyzerDATVersion>3125.0</AnalyzerDATVersion></CommonFields><Event><EventID>1278</EventID><Severity>3</Severity><GMTTime>2017-10-06T11:17:35</GMTTime><CommonFields><ThreatCategory>av.detect</ThreatCategory><ThreatEventID>1278</ThreatEventID><ThreatSeverity>2</ThreatSeverity><ThreatName>EICAR test file</ThreatName><ThreatType>test</ThreatType><DetectedUTC>2017-10-06T11:17:35Z</DetectedUTC><ThreatActionTaken>IDS_ALERT_ACT_TAK_DEL</ThreatActionTaken><ThreatHandled>True</ThreatHandled><SourceHostName>TS01</SourceHostName><SourceProcessName>On-Demand Scan</SourceProcessName><TargetHostName>TS01</TargetHostName><TargetUserName>CASAA\mohab</TargetUserName><TargetFileName>C:\Users\mohab\Desktop\dell.com</TargetFileName></CommonFields><CustomFields target=\"EPExtendedEventMT\"><BladeName>IDS_BLADE_NAME_SPB</BladeName><AnalyzerContentCreationDate>2017-10-04T15:46:00Z</AnalyzerContentCreationDate><AnalyzerGTIQuery>False</AnalyzerGTIQuery><ThreatDetectedOnCreation>False</ThreatDetectedOnCreation><TargetName>dell.com</TargetName><TargetPath>C:\Users\mohab\Desktop</TargetPath><TargetHash>01c65da52c8f3e5959ce9bb405ba6372</TargetHash><TargetFileSize>70</TargetFileSize><TargetModifyTime>2017-10-06T11:16:03Z</TargetModifyTime><TargetAccessTime>2017-10-06T11:16:03Z</TargetAccessTime><TargetCreateTime>2017-10-06T11:16:03Z</TargetCreateTime><Cleanable>False</Cleanable><TaskName>IDS_ODS_TASK_NAME_RIGHT_CLICK</TaskName><FirstAttemptedAction>IDS_ALERT_THACT_ATT_CLE</FirstAttemptedAction><FirstActionStatus>False</FirstActionStatus><SecondAttemptedAction>IDS_ALERT_THACT_ATT_DEL</SecondAttemptedAction><SecondActionStatus>True</SecondActionStatus><AttackVectorType>4</AttackVectorType><DurationBeforeDetection>92</DurationBeforeDetection><NaturalLangDescription>IDS_NATURAL_LANG_ODS_DETECTION_DELETED|TargetName=dell.com|TargetPath=C:\Users\mohab\Desktop|ThreatName=EICAR test file|ThreatType=test|TaskName=IDS_ODS_TASK_NAME_RIGHT_CLICK|TargetUserName=CASAA\mohab</NaturalLangDescription><AccessRequested></AccessRequested><AMCoreContentVersion>3125.0</AMCoreContentVersion></CustomFields></Event></SoftwareInfo></EPOevent>\n")
    message = mt.render(mark="<165>1", host=host)

    sendsingle(message)

    st = env.from_string("search index=epav host=\"{{ host }}\" sourcetype=\"mcafee:epo:syslog\" | head 2")
    search = st.render(host=host)

    resultCount, eventCount = splunk_single(setup_splunk, search)

    record_property("host", host)
    record_property("resultCount", resultCount)
    record_property("message", message)

    assert resultCount == 1
